name: noor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  adhan: ^2.0.0+1
  auto_size_text: ^3.0.0
  connectivity_plus: ^6.1.5
  cupertino_icons: ^1.0.8
  dashed_circular_progress_bar: ^0.0.6
  dio: ^5.9.0
  dotted_border: ^3.1.0
  dotted_line: ^3.2.3
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.1
  flutter_native_splash: ^2.4.6
  flutter_qiblah: ^3.1.0+1
  flutter_svg: ^2.2.0
  flutter_timezone: ^4.1.1
  font_awesome_flutter: ^10.9.1
  geocoding: ^4.0.0
  geolocator: ^13.0.4
  get_it: ^8.2.0
  google_maps_flutter: ^2.12.3
  google_nav_bar: ^5.0.7
  highlight_text: ^1.8.0
  hijri: ^3.0.0
  injectable: ^2.5.1
  intl: ^0.20.2
  jhijri_picker: ^1.0.1
  json_annotation: ^4.9.0
  marquee: ^2.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  piri_qiblah: ^0.0.2
  rflutter_alert: ^2.0.7
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.5.3
  sleek_circular_slider: ^2.1.0
  sqlite3: ^2.9.0
  sqlite3_flutter_libs: ^0.5.39
  syncfusion_flutter_core: ^30.2.7
  syncfusion_flutter_datepicker: ^30.2.7
  timezone: ^0.10.1
  url_launcher: ^6.3.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.6.0
  drift_dev: ^2.28.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/
    - assets/database/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans/PlusJakartaSans-SemiBold.ttf
          weight: 600
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600 
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
            
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 400
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/AmiriQuran-Regular.ttf
    - family: Elgharib
      fonts:
        - asset: assets/fonts/Elgharib.-A579.ttf
    - family: KFGQPC_Uthmanic
      fonts:
        - asset: assets/fonts/KFGQPC Uthmanic Script HAFS Regular.otf
    - family: ArabicTwoBold
      fonts:
        - asset: assets/fonts/ArabicTwo Bold.ttf
    - family: ScheherazadeNew-Regular
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
    - family: Tasbih
      fonts:
        - asset: assets/fonts/font_icons/Sibha.ttf
    - family: Quran
      fonts:
        - asset: assets/fonts/font_icons/Quran.ttf
    - family: Dua
      fonts:
        - asset: assets/fonts/font_icons/Dua.ttf
    - family: MeQuran
      fonts:
        - asset: assets/fonts/Me_quran Regular.ttf
    - family: HafsSmart_08
      fonts:
        - asset: assets/fonts/HafsSmart_08.ttf
    - family: DS-DIGI
      fonts:
        - asset: assets/fonts/DS-DIGI.TTF

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/helpers/
  filename: assets_helper.dart

flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#348C7C"
  adaptive_icon_foreground: assets/images/png/app_icon.png
  adaptive_icon_foreground_inset: 15
  ios: true
  image_path: assets/images/png/app_icon.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#348C7C"
  background_image: assets/images/png/app_icon.png
  branding: assets/images/png/branding.png
  branding_mode: bottom
  branding_bottom_padding: 24

  android_12:
    image: assets/images/png/app_icon.png
    icon_background_color: "#348C7C"
    branding: assets/images/png/branding.png
flutter_intl:
  enabled: true
