name: noor
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  path_provider: ^2.1.5
  sleek_circular_slider: ^2.1.0
  marquee: ^2.3.0
  font_awesome_flutter: ^10.9.1
  adhan: ^2.0.0+1
  intl: ^0.20.2
  hijri: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.1
  build_runner: ^2.6.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600  
    - family: Tasbih
      fonts:
        - asset: assets/fonts/font_icons/Sibha.ttf
    - family: Quran
      fonts:
        - asset: assets/fonts/font_icons/Quran.ttf    
  

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/helpers/
  filename: assets_helper.dart 
  